#!/usr/bin/env bash

clone-and-update-repo 'https://github.com/zsh-users/zsh-autosuggestions.git' develop dependencies/zsh-autosuggestions
clone-and-update-repo 'https://github.com/so-fancy/diff-so-fancy' master dependencies/diff-so-fancy
clone-and-update-repo 'https://github.com/tpope/vim-sensible.git' master dependencies/vim-sensible

cat <<-EOF > "$__DOTS_DIR/shell/.zshrc"
	# this file is auto generated by a script, modifications will be overwritten
	source "$__DOTS_DIR/dotprofile/dots.zsh"
EOF

rm -rf "$__DOTS_DIR/build/"
cp -r "$__DOTS_DIR/config/" "$__DOTS_DIR/build/"

mkdir -p "$__DOTS_DIR/build/.local/share/git/"
mkdir -p "$__DOTS_DIR/build/.zsh/"
mkdir -p "$__DOTS_DIR/bin/.bin/"
mkdir -p "$__DOTS_DIR/build/.vim/pack/vendor/start"

ln -sfn "$__DOTS_DIR/dependencies/diff-so-fancy/diff-so-fancy" "$__DOTS_DIR/bin/.bin/diff-so-fancy"
ln -sfn "$__DOTS_DIR/dependencies/zsh-autosuggestions/" "$__DOTS_DIR/build/.zsh/zsh-autosuggestions"
ln -sfn "$__DOTS_DIR/dependencies/vim-sensible/" "$__DOTS_DIR/build/.vim/pack/vendor/start/vim-sensible"

curl --silent -o "$__DOTS_DIR/build/.local/share/git/git-prompt.sh" "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
