#!/usr/bin/env bash

rm -rf "$__DOTS_DIR/install/build/"
mkdir -p "$__DOTS_DIR/install/build/"

clone-and-update-repo 'https://github.com/zsh-users/zsh-autosuggestions.git' develop install/build/.zsh/zsh-autosuggestions
clone-and-update-repo 'https://github.com/so-fancy/diff-so-fancy' master install/build/.local/bin/diff-so-fancy
clone-and-update-repo 'https://github.com/tpope/vim-sensible.git' master install/build/.vim/pack/start/vim-sensible

mkdir -p "$__DOTS_DIR/install/build/root"
cat <<-EOF > "$__DOTS_DIR/install/build/root/.zshrc"
	# this file is auto generated by a script, modifications will be overwritten
	source "$__DOTS_DIR/dotprofile/dots.zsh"
EOF

mkdir -p "$__DOTS_DIR/install/build/.local/share/git/"
curl --silent -o "$__DOTS_DIR/install/build/.local/share/git/git-prompt.sh" "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
ln -s
