#!/usr/bin/env bash

rm -rf "$__DOTS_DIR/build/"
cp -r "$__DOTS_DIR/static/" "$__DOTS_DIR/build/"

clone-and-update-repo 'https://github.com/zsh-users/zsh-autosuggestions.git' develop zsh-autosuggestions .zsh/zsh-autosuggestions
# TODO remove if delta is better
clone-and-update-repo 'https://github.com/so-fancy/diff-so-fancy' master diff-so-fancy .local/bin/diff-so-fancy
clone-and-update-repo 'https://github.com/tpope/vim-sensible.git' master vim-sensible .vim/pack/start/vim-sensible

download-with-cache "git-prompt.sh" "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
copy-cached "git-prompt.sh" "$__DOTS_DIR/build/.local/share/git"

cat <<-EOF > "$__DOTS_DIR/build/.zshrc"
	# this file is auto generated by a script, modifications will be overwritten
	source "$__DOTS_DIR/dotprofile/dots.zsh"
EOF
